# Generated by Django 4.1.13 on 2024-04-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_tag_quote_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='quote_count',
            field=models.IntegerField(default=0),
        ),
    ]
